### ISSUE TITLE
Export Defect on Devices 

### ISSUE THREAD

**Issue by bkerensa** [Glucosio/glucosio-android#253]
Users on a variety of Samsung devices on various. Versions of Android continue to have issues with export. We are only seeing this in a small subset of users though and on my testing on Samsung hardware the issue is not reproducible.

That said this issue is resulting in continued negative feedback and uninstalls and needs to be a top priority for us to try and identify the cause and provide a fix.

We should collect all hardware profiled and Android versions and try and identify the issue here. We can consult outside sources of expertise to troubleshoot but we need a fix.

**Comment by emartynov** [comment]
What exactly do they report and what devices do they have?

**Comment by bkerensa** [comment]
@PaoloRotolo Any reason this was closed? We still do not have a resolution do we?

**Comment by PaoloRotolo** [comment]
I thought I fixed it in that commit. Apparently new unsupported devices are coming out.

**Comment by bkerensa** [comment]
Closing this as looking at user email it appears they were running an older version we can reopen if this pops up with latest release

**Comment by Muges** [comment]
I still have this issue with the latest version from F-Droid. When I try to export in a csv file a snackbar with the message "No readings to export." is displayed, and an empty CSV file is created.

Glucosio version: 1.2.0-FOSS from F-Droid
Device: Nexus 4
OS: Android 5.1.1 (Omnirom 20160108)

**Comment by Ghazghkull** [comment]
I use the Samsung S6 with the last release and still I have this problem

**Comment by paolorotolo** [comment]
Can you confirm it's Glucosio 1.3.0?

**Comment by Ghazghkull** [comment]
I can confirm you that the version is the 1.3.0... and also that I solved it locally in a separated branch, can I push to your repository?

**Comment by paolorotolo** [comment]
Awesome, we weren't able to reproduce it on our devices.
Can you open a pull request please?

**Comment by Ghazghkull** [comment]
I haven't permissions to push my local branch to your repository, if you grant me, I will do :)

**Comment by emartynov** [comment]
https://help.github.com/articles/creating-a-pull-request/

**Comment by Ghazghkull** [comment]
Thanks emartynov, but I work every day with git at my job... I know how to create a pull request :)

**Comment by eladhen** [comment]
I'm having this problem.

When I export to csv I get a bar on the screen saying "There was a problem exporting the readings. Please try again."

I'm using Glucosio 1.3.0-FOSS (Chutney)

My device is Xiaomi Redmi 3 Pro.
Running Cyanogenmod 13.0.1
